// SPDX-License-Identifier: MIT
// §9.3 CI cross-platform determinism — 100 mock replay simulations.
//
// Each game:
//   • unique seed (0xC0DE_0000 + g)
//   • 150 deterministic frames (10 s @15Hz) with EnableGameplay=true
//   • inputs generated by a seeded System.Random (platform-independent for integral ops)
//   • ReplayWriter records the game; ReplayReader replays it
//   • live_hash[f] == replay_hash[f] for every frame (replay fidelity)
//
// Combined hash:
//   xxHash64 of all 100 final-frame hashes (LE u64 each).
//   Written to MCrossPlat_{OS}-{Arch}.txt in the bin directory (CI artifact).
//   Compared against MCrossPlat_baseline.txt if present.
//
// DoD (PRD §9.3): both Windows and Linux runs produce identical combined hashes.

using System;
using System.Buffers;
using System.Buffers.Binary;
using System.IO;
using System.IO.Hashing;
using System.Runtime.InteropServices;
using MOBA.Logic.Replay;
using MOBA.Logic.Sim;
using MOBA.Shared.Protocol;

namespace MOBA.Logic.Tests;

internal static class MCrossPlat_Verify
{
    public const int GameCount   = 100;
    public const int FrameCount  = 150; // 10 s @ 15 Hz per game

    public static int Run()
    {
        Console.WriteLine($"§9.3 Cross-Platform 100 Mock Replay");
        Console.WriteLine($"  Games      : {GameCount}  frames/game={FrameCount}");
        Console.WriteLine($"  Runtime    : {RuntimeInformation.FrameworkDescription}");
        Console.WriteLine($"  OS / Arch  : {RuntimeInformation.OSDescription} / {RuntimeInformation.ProcessArchitecture}");

        int rc          = 0;
        int mismatches  = 0;

        ReadOnlySpan<byte> slots = stackalloc byte[10] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

        var combiner = new XxHash64(seed: unchecked((long)0xFEED_C0FF_EEUL));
        Span<byte> scratch8 = stackalloc byte[8];

        for (int g = 0; g < GameCount; g++)
        {
            ulong seed = 0xC0DE_0000UL + (ulong)g;
            rc |= RunOneGame(g, seed, slots, combiner, scratch8, ref mismatches);
        }

        // Final combined hash.
        Span<byte> hashBytes = stackalloc byte[8];
        combiner.GetCurrentHash(hashBytes);
        ulong combined = BinaryPrimitives.ReadUInt64LittleEndian(hashBytes);

        Console.WriteLine($"  Replay-mismatches: {mismatches}");
        Console.WriteLine($"  Combined   : 0x{combined:X16}");

        // Write per-platform artifact for diff in CI.
        string platformTag = $"{RuntimeInformation.OSArchitecture}-{RuntimeInformation.ProcessArchitecture}";
        string outFile = Path.Combine(AppContext.BaseDirectory, $"MCrossPlat_{platformTag}.txt");
        File.WriteAllText(outFile, $"0x{combined:X16}\n");
        Console.WriteLine($"  Artifact   : {outFile}");

        // Compare against committed baseline.
        string baselinePath = Path.Combine(AppContext.BaseDirectory, "MCrossPlat_baseline.txt");
        if (File.Exists(baselinePath))
        {
            string baseline = File.ReadAllText(baselinePath).Trim();
            string current  = $"0x{combined:X16}";
            if (!string.Equals(baseline, current, StringComparison.OrdinalIgnoreCase))
            {
                Console.WriteLine($"  FAIL  baseline mismatch: expected={baseline} actual={current}");
                rc = 1;
            }
            else
            {
                Console.WriteLine($"  Baseline   : OK ({baseline})");
            }
        }
        else
        {
            Console.WriteLine($"  Baseline   : (not set — run once and copy Combined into MCrossPlat_baseline.txt)");
        }

        if (rc == 0) Console.WriteLine("§9.3 PASS");
        return rc;
    }

    private static int RunOneGame(
        int g, ulong seed,
        ReadOnlySpan<byte> slots,
        XxHash64 combiner,
        Span<byte> scratch8,
        ref int mismatches)
    {
        // ── Live simulation ──────────────────────────────────────────────────────
        var live = new DeterministicWorld(seed) { EnableGameplay = true };

        // Frame-0 snapshot for replay header.
        var snapBuf = new ArrayBufferWriter<byte>(32 * 1024);
        live.WriteSnapshot(snapBuf);

        var writer = new ReplayWriter(initialCapacity: 32 * 1024);
        writer.BeginRecording(mapId: 0, seed, slots, startUnixSec: 0UL, snapBuf.WrittenSpan);

        // Deterministic inputs: use integer-only Random seeded per game so no float.
        var rng    = new Random((int)((seed ^ (seed >> 32)) & 0x7FFF_FFFF));
        var inputs = new InputFrame[DeterministicWorld.PlayerCount];
        var liveHashes = new ulong[FrameCount];

        for (int f = 0; f < FrameCount; f++)
        {
            for (int i = 0; i < 10; i++)
            {
                inputs[i] = new InputFrame
                {
                    JoyX         = (sbyte)rng.Next(-100, 101),
                    JoyY         = (sbyte)rng.Next(-100, 101),
                    SkillBits    = (byte)rng.Next(0, 16),
                    AimAngleDeg  = (ushort)rng.Next(0, 360),
                    TargetSlot   = 0,
                    Flags        = 0,
                    Pad          = 0,
                    BuyItemId    = 0,
                };
            }
            writer.RecordTick(inputs);
            live.Tick(inputs);
            liveHashes[f] = live.Hash();
        }

        var replayBytes = writer.Finish();

        // ── Replay simulation ────────────────────────────────────────────────────
        var reader    = new ReplayReader();
        reader.Open(replayBytes);
        var rep       = new DeterministicWorld(reader.Seed) { EnableGameplay = true };
        var repInputs = new InputFrame[DeterministicWorld.PlayerCount];
        bool replayOk = true;

        for (uint f = 0; f < reader.DurationFrames; f++)
        {
            reader.GetTick(f, repInputs);
            rep.Tick(repInputs);
            if (rep.Hash() != liveHashes[(int)f])
            {
                Console.WriteLine($"  FAIL game {g:D3} seed=0x{seed:X16} replay diverged at frame {f}");
                mismatches++;
                replayOk = false;
                break;
            }
        }

        if (!replayOk) return 1;

        // Feed final hash into combined hasher.
        BinaryPrimitives.WriteUInt64LittleEndian(scratch8, liveHashes[FrameCount - 1]);
        combiner.Append(scratch8);
        return 0;
    }
}
